[package]
name = "breaks-into"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
